### ISSUE TITLE
Can we close and/or rediect this repo?

### ISSUE THREAD

**Issue by BigBlueHat** [w3c/annotation-model#1]
@iherman could we at least update the README? 😃 It's confusing if you're looking for Web Annotation or even Open Annotation content on GitHub.

Thanks!
🎩

**Comment by BigBlueHat** [comment]
Ideally, this would be re-pointed to https://github.com/w3c/web-annotation

**Comment by iherman** [comment]
I did not even know its existence. How did you find it? Is there a place which refers to it? Because if it is not referred from anywhere, I would opt to delete it.

**Comment by iherman** [comment]
I have updated the readme.
